--------------------------------------------------------
--  File created - Thursday-October-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER_SERVICING_AG
--------------------------------------------------------

  CREATE TABLE "TRAINING"."CUSTOMER_SERVICING_AG" 
   (	"CUSTID" NUMBER, 
	"CUSTNAME" VARCHAR2(20 BYTE), 
	"CUSTMOBNUM" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
REM INSERTING into TRAINING.CUSTOMER_SERVICING_AG
SET DEFINE OFF;
Insert into TRAINING.CUSTOMER_SERVICING_AG (CUSTID,CUSTNAME,CUSTMOBNUM) values (108,'Darth Vader',1236876676);
Insert into TRAINING.CUSTOMER_SERVICING_AG (CUSTID,CUSTNAME,CUSTMOBNUM) values (302,'Shubham',1234565789);
Insert into TRAINING.CUSTOMER_SERVICING_AG (CUSTID,CUSTNAME,CUSTMOBNUM) values (301,'Ayush',3335151843);
--------------------------------------------------------
--  DDL for Index SYS_C0094901
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAINING"."SYS_C0094901" ON "TRAINING"."CUSTOMER_SERVICING_AG" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_SERVICING_AG
--------------------------------------------------------

  ALTER TABLE "TRAINING"."CUSTOMER_SERVICING_AG" ADD PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING"  ENABLE;
