--------------------------------------------------------
--  File created - Thursday-October-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POLICY_AG
--------------------------------------------------------

  CREATE TABLE "TRAINING"."POLICY_AG" 
   (	"POLICYID" NUMBER, 
	"POLICYTYPE" VARCHAR2(20 BYTE), 
	"POLICYPREMIUMAMOUNT" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
REM INSERTING into TRAINING.POLICY_AG
SET DEFINE OFF;
Insert into TRAINING.POLICY_AG (POLICYID,POLICYTYPE,POLICYPREMIUMAMOUNT) values (201,'TypeA','2000');
Insert into TRAINING.POLICY_AG (POLICYID,POLICYTYPE,POLICYPREMIUMAMOUNT) values (202,'TypeB','3000');
Insert into TRAINING.POLICY_AG (POLICYID,POLICYTYPE,POLICYPREMIUMAMOUNT) values (123,'Type 4','1000');
Insert into TRAINING.POLICY_AG (POLICYID,POLICYTYPE,POLICYPREMIUMAMOUNT) values (203,'TypeC','5000');
Insert into TRAINING.POLICY_AG (POLICYID,POLICYTYPE,POLICYPREMIUMAMOUNT) values (678,'TYPED','1000');
--------------------------------------------------------
--  DDL for Index SYS_C0094902
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAINING"."SYS_C0094902" ON "TRAINING"."POLICY_AG" ("POLICYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
--------------------------------------------------------
--  Constraints for Table POLICY_AG
--------------------------------------------------------

  ALTER TABLE "TRAINING"."POLICY_AG" ADD PRIMARY KEY ("POLICYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING"  ENABLE;
