--------------------------------------------------------
--  File created - Thursday-October-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICES_AG
--------------------------------------------------------

  CREATE TABLE "TRAINING"."SERVICES_AG" 
   (	"SERVICEID" NUMBER, 
	"SERVICENAME" VARCHAR2(20 BYTE), 
	"SERVICECOST" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
REM INSERTING into TRAINING.SERVICES_AG
SET DEFINE OFF;
Insert into TRAINING.SERVICES_AG (SERVICEID,SERVICENAME,SERVICECOST) values (122,'Bumper Replacement',300);
Insert into TRAINING.SERVICES_AG (SERVICEID,SERVICENAME,SERVICECOST) values (102,'decor',3000);
Insert into TRAINING.SERVICES_AG (SERVICEID,SERVICENAME,SERVICECOST) values (451,'Vinyl',13000);
Insert into TRAINING.SERVICES_AG (SERVICEID,SERVICENAME,SERVICECOST) values (101,'polishing',1500);
Insert into TRAINING.SERVICES_AG (SERVICEID,SERVICENAME,SERVICECOST) values (103,'wheel balancing',5000);
--------------------------------------------------------
--  DDL for Index SYS_C0094911
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAINING"."SYS_C0094911" ON "TRAINING"."SERVICES_AG" ("SERVICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
--------------------------------------------------------
--  Constraints for Table SERVICES_AG
--------------------------------------------------------

  ALTER TABLE "TRAINING"."SERVICES_AG" ADD PRIMARY KEY ("SERVICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING"  ENABLE;
